# Generated by Django 5.0.3 on 2024-04-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisual',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='static/images/audio_visuais'),
        ),
        migrations.AddField(
            model_name='jornal',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='static/images/jornais'),
        ),
        migrations.AddField(
            model_name='revista',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='static/images/revistas'),
        ),
    ]
