# Generated by Django 5.0.3 on 2024-04-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0003_alter_pintura_data_de_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovisual',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='audio_visuais'),
        ),
        migrations.AlterField(
            model_name='jornal',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='jornais'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='livros'),
        ),
        migrations.AlterField(
            model_name='objetocultural',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='objetos_culturais'),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='data_de_criacao',
            field=models.CharField(default='s.d.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='pinturas'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='imagem',
            field=models.ImageField(default='no-photo.svg', upload_to='revistas'),
        ),
    ]
