# Generated by Django 5.0.3 on 2024-04-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0004_alter_audiovisual_imagem_alter_jornal_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetocultural',
            name='local_de_criacao',
            field=models.CharField(default='s.l.', max_length=200),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='local_de_criacao',
            field=models.CharField(default='s.l.', max_length=200),
        ),
    ]
