# Generated by Django 5.0.3 on 2024-04-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0005_alter_objetocultural_local_de_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetocultural',
            name='assunto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objetocultural',
            name='caracteristicas_fisicas',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='objetocultural',
            name='materiais',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='obs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='proprietario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='suporte',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pintura',
            name='tecnica',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
